"use strict";

// v0.9.1 PCM spectral resynthesis + grouped sound-design library.
// Harmonic templates are measured locally from the deterministic Factory Piano / Guitar /
// Fretless PCM already generated by this app. No external samples, network fetches, or
// additional AudioContext are used. The PCM is a timbral reference, not executable input.
(()=>{
  const SOURCES=new Set(["piano","guitar","fretless"]);
  const SOURCE_LABELS={piano:"Piano PCM",guitar:"Guitar PCM",fretless:"Fretless PCM"};
  const isResynthPatch=p=>Boolean(p&&p.engine_type==="sampler"&&p.instrument_model==="spectral_resynth");
  const spectralCache=new Map();
  let noiseBuffer=null;

  const RESYNTH_PARAM_DEFS=[
    ["resynth_source_a","Source A","select",["piano","guitar","fretless"]],
    ["resynth_source_b","Source B","select",["piano","guitar","fretless"]],
    ["resynth_morph","A/B Morph",0,1,.01],
    ["resynth_harmonics","Harmonics",4,32,1],
    ["resynth_brightness","Spectral Brightness",0,1,.01],
    ["resynth_pcm_mix","PCM Body",0,.65,.01],
    ["resynth_transient_mix","PCM Transient",0,1,.01],
    ["resynth_detune_cents","Source Detune",-30,30,.5],
    ["resynth_noise_mix","Air / Noise",0,.35,.01],
    ["resynth_attack_s","Attack",.001,8,.01],
    ["resynth_decay_s","Decay",.001,8,.01],
    ["resynth_sustain","Sustain",0,1,.01],
    ["resynth_release_s","Release",.01,10,.01],
    ["delay_mix","Delay Mix",0,.65,.01],
    ["master_gain","Master",.02,.35,.005]
  ];
  const RESYNTH_KEYS=new Set(RESYNTH_PARAM_DEFS.map(d=>d[0]));

  function sourceValue(value,fallback){
    const candidate=String(value||fallback).toLowerCase();
    return SOURCES.has(candidate)?candidate:fallback;
  }
  function validateResynthExtras(raw){
    const p={...(raw||{})};
    return {
      ...p,
      engine_type:"sampler",
      instrument_model:"spectral_resynth",
      resynth_source_a:sourceValue(p.resynth_source_a,"piano"),
      resynth_source_b:sourceValue(p.resynth_source_b,"guitar"),
      resynth_morph:clamp(p.resynth_morph??.35,0,1),
      resynth_harmonics:Math.round(clamp(p.resynth_harmonics??16,4,32)),
      resynth_brightness:clamp(p.resynth_brightness??.58,0,1),
      resynth_pcm_mix:clamp(p.resynth_pcm_mix??.20,0,.65),
      resynth_transient_mix:clamp(p.resynth_transient_mix??.28,0,1),
      resynth_detune_cents:clamp(p.resynth_detune_cents??5,-30,30),
      resynth_noise_mix:clamp(p.resynth_noise_mix??.02,0,.35),
      resynth_attack_s:clamp(p.resynth_attack_s??.02,.001,8),
      resynth_decay_s:clamp(p.resynth_decay_s??.50,.001,8),
      resynth_sustain:clamp(p.resynth_sustain??.68,0,1),
      resynth_release_s:clamp(p.resynth_release_s??1.10,.01,10),
      delay_time_s:clamp(p.delay_time_s??0,0,1.5),
      delay_feedback:clamp(p.delay_feedback??0,0,.75),
      delay_mix:clamp(p.delay_mix??0,0,.65),
      master_gain:clamp(p.master_gain??.18,.02,.35),
      max_polyphony:Math.round(clamp(p.max_polyphony??12,1,16))
    };
  }

  const baseValidatePatch=validatePatch;
  validatePatch=function(raw){
    const requested=Boolean(raw&&raw.instrument_model==="spectral_resynth");
    const p=baseValidatePatch(raw);
    return requested?validateResynthExtras({...p,...raw}):p;
  };

  function sourceDescriptor(name){
    if(!engine.ctx)return null;
    if(name==="piano"){
      if(typeof engine.ensurePianoSamples==="function")engine.ensurePianoSamples(60);
      const buffer=engine.sampleBuffers.get("piano_60");
      return buffer?{name,buffer,root:60,offset:0,analysisOffset:.065}:null;
    }
    if(name==="guitar"){
      if(typeof engine.ensureGuitarSamples==="function")engine.ensureGuitarSamples();
      const buffer=engine.sampleBuffers.get("guitar_64");
      return buffer?{name,buffer,root:64,offset:0,analysisOffset:.045}:null;
    }
    const buffer=engine.sampleBuffers.get("fretless");
    return buffer?{name:"fretless",buffer,root:48,offset:7.52,analysisOffset:.080}:null;
  }

  function harmonicTemplate(name,harmonics){
    const descriptor=sourceDescriptor(name);if(!descriptor)return null;
    const key=`${name}:${harmonics}:${descriptor.buffer.sampleRate}`;
    if(spectralCache.has(key))return spectralCache.get(key);
    const data=descriptor.buffer.getChannelData(0),sr=descriptor.buffer.sampleRate;
    const start=Math.floor((descriptor.offset+descriptor.analysisOffset)*sr);
    const available=Math.max(0,data.length-start),frames=Math.min(4096,available);
    if(frames<512)return null;
    const amps=new Float32Array(harmonics+1),f0=midiFreq(descriptor.root);
    for(let h=1;h<=harmonics;h++){
      const freq=f0*h;if(freq>=sr*.46)break;
      let re=0,im=0,weightSum=0;
      for(let i=0;i<frames;i++){
        const w=.5-.5*Math.cos(2*Math.PI*i/(frames-1)),x=data[start+i]*w,angle=2*Math.PI*freq*i/sr;
        re+=x*Math.cos(angle);im-=x*Math.sin(angle);weightSum+=w;
      }
      amps[h]=weightSum>0?2*Math.hypot(re,im)/weightSum:0;
    }
    let max=0;for(let h=1;h<amps.length;h++)max=Math.max(max,amps[h]);
    if(max<1e-7){amps[1]=1;max=1;}
    for(let h=1;h<amps.length;h++)amps[h]/=max;
    spectralCache.set(key,amps);return amps;
  }

  function createPcmDerivedWave(source,p){
    const harmonics=p.resynth_harmonics,amps=harmonicTemplate(source,harmonics);
    const real=new Float32Array(harmonics+1),imag=new Float32Array(harmonics+1);
    if(!amps){imag[1]=1;return engine.ctx.createPeriodicWave(real,imag);}
    const tilt=(p.resynth_brightness-.5)*1.55;
    for(let h=1;h<=harmonics;h++){
      const measured=amps[h]||0;
      const shaped=measured*Math.pow(h,tilt)*Math.exp(-h*(1-p.resynth_brightness)*.018);
      imag[h]=clamp(shaped,0,2.4);
    }
    if(Math.abs(imag[1])<.02)imag[1]=.02;
    return engine.ctx.createPeriodicWave(real,imag,{disableNormalization:false});
  }

  function ensureNoiseBuffer(){
    if(noiseBuffer&&noiseBuffer.sampleRate===engine.ctx.sampleRate)return noiseBuffer;
    const sr=engine.ctx.sampleRate,length=Math.ceil(.45*sr),buffer=engine.ctx.createBuffer(1,length,sr),data=buffer.getChannelData(0),noise=engine.seededNoise(90909);
    let lp=0;for(let i=0;i<length;i++){const n=noise();lp=lp*.88+n*.12;data[i]=(n-lp)*.55;}
    noiseBuffer=buffer;return buffer;
  }

  function playPcmLayer(descriptor,note,now,gainValue,duration,destination,highpass=false){
    if(!descriptor||gainValue<=.001)return null;
    const available=Math.max(.01,descriptor.buffer.duration-descriptor.offset),slice=Math.min(duration,available);
    const source=engine.ctx.createBufferSource(),gain=engine.ctx.createGain(),filter=engine.ctx.createBiquadFilter();
    source.buffer=descriptor.buffer;source.playbackRate.value=clamp(Math.pow(2,(note-descriptor.root)/12),.35,3);
    gain.gain.value=gainValue;filter.type=highpass?"highpass":"lowpass";filter.frequency.value=highpass?720:11000;filter.Q.value=.65;
    source.connect(filter);filter.connect(gain);gain.connect(destination);source.start(now,descriptor.offset,slice);return source;
  }

  engine.playSpectralResynth=function(midiNote,velocity,whenSeconds){
    const note=clamp(Math.round(midiNote),0,127);this.limitVoices(note);
    const p=validateResynthExtras(this.patch),now=this.ctx.currentTime+Math.max(0,Number(whenSeconds)||0),vel=clamp(velocity,0,1);
    const f=midiFreq(note+(Number(p.octave_shift)||0)*12),morph=p.resynth_morph;
    const voiceGain=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();
    const dry=this.ctx.createGain(),delay=this.ctx.createDelay(1.5),feedback=this.ctx.createGain(),wet=this.ctx.createGain();
    filter.type="lowpass";filter.frequency.value=clamp(900+Math.pow(p.resynth_brightness,1.35)*16500,700,18000);filter.Q.value=.62+p.resynth_brightness*1.9;
    dry.gain.value=1-p.delay_mix;wet.gain.value=p.delay_mix;delay.delayTime.value=p.delay_time_s;feedback.gain.value=p.delay_feedback;
    filter.connect(voiceGain);voiceGain.connect(dry);dry.connect(this.master);voiceGain.connect(delay);delay.connect(feedback);feedback.connect(delay);delay.connect(wet);wet.connect(this.master);

    const oscA=this.ctx.createOscillator(),oscB=this.ctx.createOscillator(),gainA=this.ctx.createGain(),gainB=this.ctx.createGain();
    oscA.setPeriodicWave(createPcmDerivedWave(p.resynth_source_a,p));oscB.setPeriodicWave(createPcmDerivedWave(p.resynth_source_b,p));
    oscA.frequency.value=f;oscB.frequency.value=f;oscB.detune.value=p.resynth_detune_cents;
    gainA.gain.value=Math.sqrt(1-morph);gainB.gain.value=Math.sqrt(morph);oscA.connect(gainA);oscB.connect(gainB);gainA.connect(filter);gainB.connect(filter);

    const sources=[];
    const descA=sourceDescriptor(p.resynth_source_a),descB=sourceDescriptor(p.resynth_source_b);
    const bodyGain=p.resynth_pcm_mix*.32*vel,transientGain=p.resynth_transient_mix*.34*vel;
    const bodyDuration=.16+p.resynth_pcm_mix*.70;
    const aBody=playPcmLayer(descA,note,now,bodyGain*(1-morph),bodyDuration,filter,false);if(aBody)sources.push(aBody);
    const bBody=playPcmLayer(descB,note,now,bodyGain*morph,bodyDuration,filter,false);if(bBody)sources.push(bBody);
    const aAttack=playPcmLayer(descA,note,now,transientGain*(1-morph),.105,voiceGain,true);if(aAttack)sources.push(aAttack);
    const bAttack=playPcmLayer(descB,note,now,transientGain*morph,.105,voiceGain,true);if(bAttack)sources.push(bAttack);

    if(p.resynth_noise_mix>.002){
      const noise=this.ctx.createBufferSource(),noiseFilter=this.ctx.createBiquadFilter(),noiseGain=this.ctx.createGain();
      noise.buffer=ensureNoiseBuffer();noise.loop=true;noiseFilter.type="bandpass";noiseFilter.frequency.value=1400+p.resynth_brightness*5200;noiseFilter.Q.value=.55;
      noiseGain.gain.value=p.resynth_noise_mix*.18*vel;noise.connect(noiseFilter);noiseFilter.connect(noiseGain);noiseGain.connect(filter);noise.start(now);sources.push(noise);
    }

    const peak=Math.max(.015,vel*.86),attackEnd=now+p.resynth_attack_s,decayEnd=attackEnd+p.resynth_decay_s;
    voiceGain.gain.setValueAtTime(.0001,now);voiceGain.gain.exponentialRampToValueAtTime(peak,attackEnd);voiceGain.gain.linearRampToValueAtTime(Math.max(.0001,peak*p.resynth_sustain),decayEnd);
    oscA.start(now);oscB.start(now);
    this.voices.set(note,{kind:"resynth",oscillators:[oscA,oscB],sources,voiceGain});setPerformanceActive(note,true);
  };

  const baseNoteOn=engine.noteOn.bind(engine);
  const baseNoteOff=engine.noteOff.bind(engine);
  engine.noteOn=function(midiNote,velocity=.85,whenSeconds=0){
    if(isResynthPatch(this.patch)){this.playSpectralResynth(midiNote,velocity,whenSeconds);return;}
    return baseNoteOn(midiNote,velocity,whenSeconds);
  };
  engine.noteOff=function(midiNote,whenSeconds=0){
    const note=clamp(Math.round(midiNote),0,127),voice=this.voices.get(note);
    if(voice&&voice.kind==="resynth"){
      const now=this.ctx.currentTime+Math.max(0,Number(whenSeconds)||0),p=validateResynthExtras(this.patch),stop=now+p.resynth_release_s+.12;
      voice.voiceGain.gain.cancelScheduledValues(now);voice.voiceGain.gain.setTargetAtTime(.0001,now,Math.max(.008,p.resynth_release_s/5));
      for(const oscillator of voice.oscillators){try{oscillator.stop(stop);}catch(_){}}
      for(const source of voice.sources){try{source.stop(stop);}catch(_){}}
      this.voices.delete(note);setPerformanceActive(note,false);return;
    }
    return baseNoteOff(midiNote,whenSeconds);
  };

  const baseEngineDetail=engineDetail;
  engineDetail=function(p){
    if(isResynthPatch(p)){
      const a=SOURCE_LABELS[p.resynth_source_a]||p.resynth_source_a,b=SOURCE_LABELS[p.resynth_source_b]||p.resynth_source_b;
      return `PCM Spectral Resynthesis · ${a} ↔ ${b} · ${p.resynth_harmonics} harmonics`;
    }
    return baseEngineDetail(p);
  };

  const baseRenderParameters=renderParameters;
  function displayValue(key,value){
    if(key==="resynth_source_a"||key==="resynth_source_b")return SOURCE_LABELS[value]||String(value);
    if(key==="resynth_harmonics")return String(Math.round(value));
    if(key==="resynth_detune_cents")return `${Number(value).toFixed(1)} ct`;
    if(key.endsWith("_s"))return `${Number(value).toFixed(2)} s`;
    if(key==="master_gain")return Number(value).toFixed(2);
    if(typeof value==="number"&&value>=0&&value<=1)return `${Math.round(value*100)}%`;
    return String(value);
  }
  renderParameters=function(){
    if(!isResynthPatch(currentPatch))return baseRenderParameters();
    const root=document.getElementById("params");root.innerHTML="";
    for(const def of RESYNTH_PARAM_DEFS){
      const [key,label,kindOrMin,max,step]=def,card=document.createElement("div");card.className="param-control";
      const value=currentPatch[key],header=document.createElement("div");header.className="param-control-head";header.innerHTML=`<span>${label}</span><output>${displayValue(key,value)}</output>`;card.appendChild(header);
      if(kindOrMin==="select"){
        const select=document.createElement("select");select.dataset.param=key;
        for(const optionValue of max){const option=new Option(SOURCE_LABELS[optionValue]||optionValue,optionValue);select.append(option);}select.value=value;
        select.addEventListener("change",()=>applyParam(key,select.value));card.appendChild(select);
      }else{
        const min=kindOrMin,input=document.createElement("input");input.type="range";input.min=min;input.max=max;input.step=step;input.value=value;input.dataset.param=key;
        input.addEventListener("input",()=>{const n=Number(input.value);applyParam(key,n,false);header.querySelector("output").textContent=displayValue(key,n);});
        input.addEventListener("change",()=>renderParameters());card.appendChild(input);
      }
      root.appendChild(card);
    }
  };

  const baseApplyParam=applyParam;
  applyParam=function(key,value,rerender=true){
    if(!isResynthPatch(currentPatch)||!RESYNTH_KEYS.has(key))return baseApplyParam(key,value,rerender);
    const next=validateResynthExtras({...currentPatch,[key]:value});engine.setPatchWithRender(next,false);currentPatch=engine.patch;
    spectralCache.clear();if(rerender)renderParameters();document.getElementById("status").textContent=`${key} を調整しました。`;
  };

  const baseRenderPatch=renderPatch;
  renderPatch=function(){
    baseRenderPatch();if(isResynthPatch(currentPatch))document.getElementById("engineBadge").textContent="RESYNTH";
  };

  const SOUND_LIBRARY_GROUPS=[
    ["pcm","実楽器 / PCM",[
      ["Grand Piano","コンサートホールで弾く豊かなグランドピアノ。自然なハンマーのアタックと長い響板の余韻。"],
      ["Soft Grand","柔らかく暖かいグランドピアノ。ハンマーは控えめで、近く自然な響き。"],
      ["Rock Guitar","ロック向けのエレキギター。強いピッキングとクランチ寄りのアンプ。"],
      ["Fusion Guitar","フュージョン向けの滑らかなエレキギター。クリーン寄りで少しコーラス。"],
      ["Acoustic Guitar","アコースティックギター。木質で自然、ピックのアタックは明瞭。"],
      ["Fretless Bass","歌うフレットレスベース。指弾きノイズとスライド、太い低域。"],
      ["Dry Drums","タイトでドライなドラムセット。近くパンチがあり余韻は短い。"],
      ["Shuffle Drums","ハーフタイムシャッフル向けのドラムセット。太いキックと抜けるスネア。"],
      ["DX-style EP","80年代DX-7風のきらびやかなFMエレピ。硬いアタックと透明な余韻。"]
    ]],
    ["pad","Pad / Atmosphere",[
      ["Warm Analog Pad","暖かく太いアナログパッド。柔らかく立ち上がり、広がりのある長い余韻。"],
      ["Airy Choir Pad","息の成分があるエアリーなクワイアパッド。柔らかく遠くに広がる長い余韻。"],
      ["Dark Cinematic Pad","暗く重いシネマティックパッド。ゆっくり立ち上がり、広い空間に長く残る。"],
      ["Glass Ambient Pad","ガラスのように透明で冷たいアンビエントパッド。遠く、広く、ゆっくり変化する。"],
      ["Dreamy Wide Pad","夢の中のような柔らかいワイドパッド。薄い空気感と長い残響。"],
      ["Organic String Pad","弦のような有機的なパッド。暖かく滑らかで、PCMの生っぽさを少し残す。"]
    ]],
    ["keys","Keys / Organ",[
      ["Analog Synth Keys","柔らかく暖かいアナログのシンセキー。適度なアタックと自然な余韻。"],
      ["Bright Poly Keys","明るく抜けるポリシンセ鍵盤。速いアタック、少しワイドで短めの余韻。"],
      ["Crystal Keys","クリスタルのように透明なシンセキー。硬いアタック、明るい倍音、控えめな残響。"],
      ["Soft Bell Keys","ベルと鍵盤の中間。柔らかいアタックだが高域に透明な倍音が残る。"],
      ["PCM Organ","暖かく滑らかなオルガン。アタックは弱く、持続音が太く安定している。"],
      ["Retro Polysynth","80年代の太いポリシンセ。少しワイドで明るく、レトロな電子感。"]
    ]],
    ["lead","Lead / Brass",[
      ["Synth Brass","パンチのあるシンセブラス。明るく厚く、速いアタック。"],
      ["Soft Brass","柔らかく暖かいブラス。アタックは少し遅く、太く滑らかな持続音。"],
      ["Singing Lead","歌うような滑らかなリード。フレットレスのような有機感と長めの余韻。"],
      ["Metallic Lead","金属的で鋭いリード。明るい倍音と硬いアタック、短い残響。"],
      ["Wide Fusion Lead","フュージョン向けの太く広いリード。滑らかで少しギター弦の質感。"],
      ["Airy Solo Lead","息を含む柔らかいソロリード。軽いノイズ感と広い空間。"]
    ]],
    ["pluck","Pluck / Bell",[
      ["Glass Bell","ガラスと金属が混ざった明るいベル。硬いアタックと長い余韻。"],
      ["Crystal Bell","冷たく透明なクリスタルベル。細く明るい倍音が長く残る。"],
      ["Wooden Pluck","木質で短いアタックのプラック。ギター弦のような有機感を少し残す。"],
      ["Harp Pluck","ハープのような柔らかい撥弦音。自然で暖かく、中程度の余韻。"],
      ["Marimba Hybrid","マリンバとシンセの中間。木質でパーカッシブ、丸い高域、短い余韻。"],
      ["Digital Pluck","デジタルで硬い短いプラック。鋭い高域とドライな質感。"]
    ]],
    ["bass","Bass",[
      ["Warm Synth Bass","暖かく太いシンセベース。アタックは速く、高域は丸く、余韻は短め。"],
      ["Dark Analog Bass","暗く重いアナログベース。太い低域と短い余韻、ノイズは少ない。"],
      ["Acid Bass","レゾナンス感の強いアシッドベース。硬いアタックと明るい倍音。"],
      ["Plucked Bass","弦を弾いたようなベース。木質で速いアタック、PCMの生っぽさを残す。"],
      ["Air Bass","空気を含む柔らかいベース。暗めで丸く、少し遠い空間感。"],
      ["Metal Bass","金属的で鋭いシンセベース。明るい倍音、硬いアタック、ドライ。"]
    ]],
    ["voice","Strings / Voice",[
      ["String Ensemble","広がりのあるシンセストリングス。暖かく滑らかで長いサステイン。"],
      ["Soft Strings","柔らかく近いストリングス。暗めで暖かく、アタックはゆっくり。"],
      ["Airy Choir","息のある明るいクワイア。柔らかく広く、長い余韻。"],
      ["Dark Choir","暗く遠いクワイア。低い倍音が太く、長い残響。"],
      ["Vocal Pad","人の声のようなパッド。滑らかで有機的、少し空気を含む。"],
      ["Pizzicato Strings","木質で短いピチカートストリングス。速いアタック、自然でドライ。"]
    ]]
  ];

  function buildSoundDesignLibrary(){
    const host=document.querySelector("#soundDesign .chips");if(!host)return;
    host.innerHTML="";host.style.display="grid";host.style.gap="10px";
    const controls=document.createElement("div");controls.style.cssText="display:grid;grid-template-columns:minmax(180px,.45fr) minmax(220px,1fr) auto;gap:8px;align-items:center;";
    const category=document.createElement("select");category.id="soundPaletteCategory";category.setAttribute("aria-label","音色グループ");category.style.cssText="min-height:42px;color:#eef1ff;background:#171b29;border:1px solid #3a405d;border-radius:12px;padding:8px 11px;";
    category.append(new Option("すべての音色","all"));for(const [id,label,items] of SOUND_LIBRARY_GROUPS)category.append(new Option(`${label} (${items.length})`,id));
    const search=document.createElement("input");search.id="soundPaletteSearch";search.type="search";search.placeholder="音色を検索（例: 木質、ベル、暖かい）";search.setAttribute("aria-label","音色ライブラリを検索");search.style.cssText="min-height:42px;color:#eef1ff;background:#0e1019;border:1px solid #343a56;border-radius:12px;padding:8px 11px;";
    const count=document.createElement("span");count.id="soundPaletteCount";count.style.cssText="color:#9ca6c4;font-size:.82rem;white-space:nowrap;";
    controls.append(category,search,count);
    const grid=document.createElement("div");grid.id="soundPaletteGrid";grid.className="chips";grid.style.marginTop="0";
    host.append(controls,grid);

    const all=SOUND_LIBRARY_GROUPS.flatMap(([id,group,items])=>items.map(([label,prompt])=>({id,group,label,prompt})));
    const render=()=>{
      grid.innerHTML="";const q=search.value.trim().toLowerCase(),selected=category.value;
      const shown=all.filter(item=>(selected==="all"||item.id===selected)&&(!q||`${item.label} ${item.prompt} ${item.group}`.toLowerCase().includes(q)));
      for(const item of shown){
        const button=document.createElement("button");button.type="button";button.dataset.prompt=item.prompt;button.title=`${item.group}: ${item.prompt}`;button.textContent=item.label;
        button.addEventListener("click",()=>{document.getElementById("prompt").value=item.prompt;generate();});grid.appendChild(button);
      }
      count.textContent=`${shown.length} / ${all.length} 音色`;
      if(!shown.length){const empty=document.createElement("span");empty.textContent="条件に一致する音色がありません。自由入力も利用できます。";empty.style.color="#9ca6c4";grid.appendChild(empty);}
    };
    category.addEventListener("change",render);search.addEventListener("input",render);render();
    window.soundDesignLibrary={groups:SOUND_LIBRARY_GROUPS,total:all.length,render};
  }

  const eyebrow=document.querySelector(".eyebrow");if(eyebrow)eyebrow.textContent="v0.9.1 sound design · semantic PCM resynthesis";
  buildSoundDesignLibrary();
  window.synthResynthesisRuntime={isResynthPatch,validateResynthExtras,harmonicTemplate};
})();